name       : python-jinja2-time
version    : 0.2.0
release    : 1
source     :
    - https://github.com/hackebrot/jinja2-time/archive/refs/tags/0.2.0.tar.gz : 0e647e525ba47523fa400a58fdec090b1cc6dcec4afbf095ee01e9e589e5a5ef
homepage   : https://github.com/hackebrot/jinja2-time
license    : MIT
component  : programming.python
summary    : Jinja2 Extension for Dates and Times
description: |
    Jinja2 Extension for Dates and Times. 
builddeps  :
    - python-arrow
    - python-freezegun
    - python-jinja
    - python-pytest
rundeps    :
    - python-arrow
    - python-jinja
setup      : |
    %patch -p1 < $pkgfiles/python-jinja-time-0.2.0-arrow_shift.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
